export const ACTION_QUIZ_ADD = 'ACTION_QUIZ_ADD'
export const ACTION_QUIZ_LIST = 'ACTION_QUIZ_LIST'
export const ACTION_QUIZ_LIST_FAIL = 'ACTION_QUIZ_LIST_FAIL'
export const ACTION_QUIZ_GET = 'ACTION_QUIZ_GET'
export const ACTION_QUIZ_GET_FAIL = 'ACTION_QUIZ_GET_FAIL'
export const ACTION_QUIZ_UPDATE = "ACTION_QUIZ_UPDATE"
export const ACTION_QUIZ_REMOVE = "ACTION_QUIZ_REMOVE"
export const ACTION_ANSWER_LIST = "ACTION_ANSWER_LIST"
